; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "KKTAgent"
#define MyAppVersion "1.0"
#define MyAppPublisher "5element35, LLC."
#define MyAppURL "https://www.kassbot.website/"
#define MyAppExeName "kktagent.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{00A72831-7ADC-459F-9357-373A7066DF0F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=C:\projects\kktagent\dist\license.txt
InfoBeforeFile=C:\projects\kktagent\dist\beforeinstall.txt
InfoAfterFile=C:\projects\kktagent\dist\afterinstall.txt
; Uncomment the following line to run in non administrative install mode (install for current user only.)
PrivilegesRequired=none
OutputDir=C:\projects\kktagent\msi
OutputBaseFilename=kktagentsetupp
SetupIconFile=C:\projects\kktagent\dist\Ebiene-E-Commerce-Cash-register.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Files]
Source: "C:\projects\kktagent\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\ProgramData\V_element\kktagent\.secrets.toml"; DestDir: "C:\ProgramData\V_element\kktagent\"
Source: "C:\ProgramData\V_element\kktagent\settings.toml"; DestDir: "C:\ProgramData\V_element\kktagent\"

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Parameters: "install";  WorkingDir: "{app}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: runhidden
Filename: "{app}\{#MyAppExeName}"; Parameters: "start";  WorkingDir: "{app}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: runhidden

[UninstallRun]
Filename: "{app}\{#MyAppExeName}"; Parameters: "remove";  WorkingDir: "{app}";